model:
  d_fft: 1024
  d_model: 512
  dropout: 0.1
  heads: 4
  layers: 6
  type: transformer
paths:
  checkpoint_dir: checkpoints
  data_dir: datasets
preprocessing:
  char_repeats: 3
  languages:
  - de
  - en_us
  - ukn
  lowercase: true
  n_val: 5000
  phoneme_symbols:
  - a
  - b
  - c
  - C
  - d
  - e
  - E
  - f
  - g
  - G
  - h
  - i
  - j
  - k
  - l
  - L
  - m
  - n
  - N
  - o
  - p
  - q
  - r
  - s
  - S
  - t
  - T
  - u
  - v
  - w
  - x
  - X
  - y
  - z
  - Z
  - !
  - "*"
  - 8
  - 4
  - 5
  - 7
  - 3
  - ~
  - $
  - "\xE6"
  - "\xE7"
  - "\xF0"
  - "\xF8"
  - "\u014B"
  - "\u0153"
  - "\u0250"
  - "\u0251"
  - "\u0254"
  - "\u0259"
  - "\u025B"
  - "\u025D"
  - "\u0279"
  - "\u0261"
  - "\u026A"
  - "\u0281"
  - "\u0283"
  - "\u028A"
  - "\u028C"
  - "\u028F"
  - "\u0292"
  - "\u0294"
  - "\u02C8"
  - "\u02CC"
  - "\u02D0"
  - "\u0303"
  - "\u030D"
  - "\u0325"
  - "\u0329"
  - "\u032F"
  - "\u0361"
  - "\u03B8"
  text_symbols: "abcdefghijklmnopqrstuvwxyzəɛɔéŋáíóúʉàòɗìūèǝùńűɨæøcśƴćɓýðǹɲɦƌŧåɖđABCDEFGHIJKLMNOPQRSTUVWXYZˍ˰`ʼˬ¯´ʻˈˉˆˇꞌʾⁿıɩʋɑǀɣịạọụẹșṛḳḍỗếửắằȧġṅîûâêôŵçţȩşḵṋḛᴐčšěňăžğǐĕǎŭõũãñĩẽươḡīēāōőëÿï\xE4\xF6\xFC\xC4\ 
\xD6\xDC\xDF\x300\x301\x303\x304\x302\x331\x327\x323\x330\x200\x306"
training:
  batch_size: 32
  batch_size_val: 32
  checkpoint_steps: 100000
  ddp_backend: nccl
  ddp_host: localhost
  ddp_post: '12355'
  epochs: 5000
  generate_steps: 10000
  learning_rate: 0.0001
  n_generate_samples: 10
  num_gpus: 1
  rank: 0
  scheduler_plateau_factor: 0.5
  scheduler_plateau_patience: 10
  store_phoneme_dict_in_model: true
  validate_steps: 10000
  warmup_steps: 10000
